DROP TABLE IF EXISTS account;

CREATE TABLE account(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(100) NOT NULL UNIQUE,
   addres VARCHAR(100) NOT NULL,
   password VARCHAR(100) NOT NULL,
   authority VARCHAR(100)
);