DROP TABLE IF EXISTS schedule;
CREATE TABLE schedule(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   radio1 VARCHAR(100), 
   radio2 VARCHAR(100),
   time1 VARCHAR(100), 
   time2 VARCHAR(100),
   authority VARCHAR(100)
);

DROP TABLE IF EXISTS user;

CREATE TABLE user(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(100) NOT NULL UNIQUE,
   addres VARCHAR(100) NOT NULL,
   password VARCHAR(100) NOT NULL,
   authority VARCHAR(100)
);